version: '3.8'

services:
  db:
    container_name: postgresql_db
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
